WARNING_UZ = (
    "⚠️ <b>OGOHLANTIRISH</b>\n\n"
    "<b>O'zbekiston Respublikasining Ma'muriy javobgarlik to'g'risidagi kodeksi</b>\n\n"
    "<b>40-modda. Tuhmat</b>\n"
    "Tuhmat, ya'ni bila turib yolg'on, boshqa bir shaxsni sharmanda qiluvchi uydirmalarni "
    "tarqatish — bazaviy hisoblash miqdorining yigirma baravaridan oltmish baravarigacha "
    "miqdorda jarima solishga sabab bo'ladi.\n\n"
    "<b>41-modda. Haqorat qilish</b>\n"
    "Haqorat qilish, ya'ni shaxsning sha'ni va qadr-qimmatini qasddan kamsitish — bazaviy "
    "hisoblash miqdorining yigirma baravaridan qirq baravarigacha miqdorda jarima solishga "
    "sabab bo'ladi.\n\n"
    "⚠️ <b>OGOHLANTIRISH</b>\n\n"
    "<b>O'zbekiston Respublikasining Jinoyat kodeksi</b>\n\n"
    "<b>139-modda. Tuhmat</b>\n"
    "Tuhmat qilish, ya'ni bila turib boshqa shaxsni sharmanda qiladigan uydirmalar tarqatish, "
    "shunday harakatlar uchun ma'muriy jazo qo'llanilganidan keyin sodir etilgan bo'lsa, — "
    "bazaviy hisoblash miqdorining ikki yuz baravarigacha miqdorda jarima yoki uch yuz "
    "soatgacha majburiy jamoat ishlari yoxud ikki yilgacha axloq tuzatish ishlari bilan "
    "jazolanadi.\n\n"
    "Nashr qilish yoki boshqacha usulda ko'paytirilgan tarzda, shu jumladan ommaviy axborot "
    "vositalarida, telekommunikasiya tarmoqlarida yoki Internet jahon axborot tarmog'ida "
    "joylashtirish orqali tuhmat qilish, — bazaviy hisoblash miqdorining ikki yuz baravaridan "
    "to'rt yuz baravarigacha miqdorda jarima yoki uch yuz soatdan uch yuz oltmish soatgacha "
    "majburiy jamoat ishlari yoxud ikki yildan uch yilgacha axloq tuzatish ishlari yoki bir "
    "yilgacha ozodlikni cheklash bilan jazolanadi.\n\n"
    "<b>Tuhmat:</b>\n"
    "a) og'ir yoki o'ta og'ir jinoyat sodir etishda ayblab;\n"
    "b) og'ir oqibatlar kelib chiqishiga sabab bo'lgan holda;\n"
    "v) xavfli residivist tomonidan;\n"
    "g) g'arazgo'ylik yoki boshqa past niyatlarda qilinsa, — bazaviy hisoblash miqdorining "
    "uch yuz baravaridan besh yuz baravarigacha miqdorda jarima yoki uch yuz oltmish soatdan "
    "to'rt yuz soatgacha majburiy jamoat ishlari yoxud bir yildan uch yilgacha ozodlikni "
    "cheklash bilan jazolanadi.\n\n"
    "<b>140-modda. Haqorat qilish</b>\n"
    "Haqorat qilish, ya'ni shaxsning sha'ni va qadr-qimmatini beodoblik bilan qasddan "
    "tahqirlash, basharti, shunday harakatlar uchun ma'muriy jazo qo'llanilgandan keyin "
    "sodir etilgan bo'lsa, — bazaviy hisoblash miqdorining ikki yuz baravarigacha miqdorda "
    "jarima yoki ikki yuz qirq soatgacha majburiy jamoat ishlari yoxud bir yilgacha axloq "
    "tuzatish ishlari bilan jazolanadi.\n\n"
    "Nashr qilish yoki boshqacha usulda ko'paytirilgan tarzda, shu jumladan ommaviy axborot "
    "vositalarida, telekommunikasiya tarmoqlarida yoki Internet jahon axborot tarmog'ida "
    "joylashtirish orqali haqorat qilish — bazaviy hisoblash miqdorining ikki yuz "
    "baravaridan to'rt yuz baravarigacha miqdorda jarima yoki ikki yuz qirq soatdan uch yuz "
    "soatgacha majburiy jamoat ishlari yoxud bir yildan ikki yilgacha axloq tuzatish ishlari "
    "bilan jazolanadi.\n\n"
    "<b>Haqorat qilish:</b>\n"
    "a) jabrlanuvchini o'z xizmat yoki fuqarolik burchini bajarishi munosabati bilan bog'liq "
    "holda;\n"
    "b) xavfli residivist tomonidan yoki tuhmat qilganligi uchun ilgari sudlangan shaxs "
    "tomonidan qilingan bo'lsa, — bazaviy hisoblash miqdorining to'rt yuz baravaridan olti "
    "yuz baravarigacha miqdorda jarima yoki ikki yildan uch yilgacha axloq tuzatish ishlari "
    "yoxud bir yilgacha ozodlikni cheklash bilan jazolanadi.\n\n"
    "<b>284-modda. Bo'ysunuvchining o'z boshlig'ini yoki boshliqning o'ziga bo'ysunuvchini "
    "haqorat qilishi</b>\n"
    "Bo'ysunuvchining o'z boshlig'ini, shuningdek, boshliqning o'ziga bo'ysunuvchini haqorat "
    "qilishi shunday harakatlar uchun intizomiy jazo qo'llanilganidan keyin sodir etilgan "
    "bo'lsa, — ikki yilgacha xizmat bo'yicha cheklash yoki bir yilgacha ozodlikdan mahrum "
    "qilish bilan jazolanadi."
)

WARNING_RU = (
    "⚠️ <b>ПРЕДУПРЕЖДЕНИЕ</b>\n\n"
    "<b>Кодекс Республики Узбекистан об административной ответственности</b>\n\n"
    "<b>Статья 40. Клевета</b>\n"
    "Клевета, то есть распространение заведомо ложных, позорящих другое лицо измышлений, — "
    "влечет наложение штрафа от двадцати до шестидесяти базовых расчетных величин.\n\n"
    "<b>Статья 41. Оскорбление</b>\n"
    "Оскорбление, то есть умышленное унижение чести и достоинства личности — влечет "
    "наложение штрафа от двадцати до сорока базовых расчетных величин.\n\n"
    "⚠️ <b>ПРЕДУПРЕЖДЕНИЕ</b>\n\n"
    "<b>Уголовный кодекс Республики Узбекистан</b>\n\n"
    "<b>Статья 139. Клевета</b>\n"
    "Клевета, то есть распространение заведомо ложных, позорящих другое лицо измышлений, "
    "совершенная после применения административного взыскания за такие же действия, — "
    "наказывается штрафом до двухсот базовых расчетных величин или обязательными "
    "общественными работами до трехсот часов либо исправительными работами до двух лет.\n\n"
    "Клевета в печатном или иным способом размноженном виде, в том числе размещенная в "
    "средствах массовой информации, сетях телекоммуникаций или всемирной информационной "
    "сети Интернет, — наказывается штрафом от двухсот до четырехсот базовых расчетных "
    "величин или обязательными общественными работами от трехсот до трехсот шестидесяти "
    "часов либо исправительными работами от двух до трех лет или ограничением свободы до "
    "одного года.\n\n"
    "<b>Клевета:</b>\n"
    "а) соединенная с обвинением в совершении тяжкого или особо тяжкого преступления;\n"
    "б) повлекшая за собой тяжкие последствия;\n"
    "в) совершенная опасным рецидивистом;\n"
    "г) из корыстных или иных низменных побуждений — наказывается штрафом от трехсот до "
    "пятисот базовых расчетных величин или обязательными общественными работами от трехсот "
    "шестидесяти до четырехсот часов либо ограничением свободы от одного года до трех "
    "лет.\n\n"
    "<b>Статья 140. Оскорбление</b>\n"
    "Оскорбление, то есть умышленное унижение чести и достоинства личности в неприличной "
    "форме, совершенное после применения административного взыскания за такие же действия, "
    "— наказывается штрафом до двухсот базовых расчетных величин или обязательными "
    "общественными работами до двухсот сорока часов либо исправительными работами до "
    "одного года.\n\n"
    "Оскорбление в печатном или иным способом размноженном виде, в том числе размещенное в "
    "средствах массовой информации, сетях телекоммуникаций или всемирной информационной "
    "сети Интернет — наказывается штрафом от двухсот до четырехсот базовых расчетных "
    "величин или обязательными общественными работами от двухсот сорока до трехсот часов "
    "либо исправительными работами от одного года до двух лет.\n\n"
    "<b>Оскорбление:</b>\n"
    "а) в связи с выполнением потерпевшим своего служебного или гражданского долга;\n"
    "б) нанесенное опасным рецидивистом или лицом, ранее судимым за клевету, — наказывается "
    "штрафом от четырехсот до шестисот базовых расчетных величин или исправительными "
    "работами от двух до трех лет либо ограничением свободы до одного года.\n\n"
    "<b>Статья 284. Оскорбление подчиненным начальника или начальником подчиненного</b>\n"
    "Оскорбление подчиненным начальника, а равно начальником подчиненного, совершенное "
    "после наложения дисциплинарного взыскания за такие же действия, — наказывается "
    "ограничением по службе до двух лет или лишением свободы до одного года."
)
